In [1]:
import numpy as np
# Create retail data: 10 rows × 5 columns
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

print("\nORIGINAL RETAIL DATA:")
print(retail_data)
print(f"\nData shape: {retail_data.shape}")
print(f"Data type: {retail_data.dtype}")


ORIGINAL RETAIL DATA:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Data shape: (10, 5)
Data type: float64


In [ ]:
print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")


In [5]:
IM = np.eye(3)
print(IM)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print("\nQ1.2: Create an array of 10 zeros using np.zeros()")


In [6]:
ten_zeros = np.zeros(10)
print(ten_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print("\nQ1.3: Create an array of 5 ones using np.ones()")


In [8]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [ ]:
print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")


In [9]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print("\nQ1.5: Create an array with 10 evenly spaced values from 0 to 10 using np.linspace()")


In [13]:
linspace_array = np.linspace(0,10,10)
linspace_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
print("\nQ2.1: What is the shape of the retail_data array?")


In [19]:
print(f"Shape: {retail_data.shape}")


Shape: (10, 5)


In [15]:
shape = retail_data.shape
shape

(10, 5)

In [ ]:
print("\nQ2.2: What is the data type of the retail_data array?")


In [20]:
data_type = retail_data.dtype
data_type

dtype('float64')

In [21]:
print(f"Data type: {retail_data.dtype}")


Data type: float64


In [ ]:
print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")


In [22]:
size = retail_data.size
size

50

In [ ]:
print("\nQ2.4: What is the number of dimensions of the retail_data array?")


In [23]:
ndim = retail_data.ndim
ndim

2

In [ ]:
print("\nQ2.5: What is the memory size of the retail_data array in bytes?")


In [24]:
memory_size = retail_data.nbytes
memory_size

400

In [25]:
print(f"Memory size: {retail_data.nbytes} bytes")


Memory size: 400 bytes


In [ ]:
print("\nQ3.1: Extract the first row of retail_data")


In [27]:
first_row = retail_data[0]
print(first_row)

[1001.     29.99   45.      4.2    15.  ]


In [ ]:
print("\nQ3.2: Extract the last row of retail_data")


In [28]:
last_row = retail_data[-1]
print(last_row)

[1010.     59.99   34.      4.4    10.  ]


In [ ]:
print("\nQ3.3: Extract the Price column (column index 1)")


In [30]:
price = retail_data[:,1]
print(price)

[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]


In [ ]:
print("\nQ3.4: Extract the first 3 rows and first 2 columns")


In [31]:
x = retail_data[:3,:2]
x

array([[1001.  ,   29.99],
       [1002.  ,   49.99],
       [1003.  ,   19.99]])

In [ ]:
print("\nQ3.5: Extract rows 2 to 5 (inclusive)")


In [34]:
x=retail_data[1:5]
x

array([[1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ]])

In [35]:
rows_2_to_5 = retail_data[2:6]
print(rows_2_to_5)


[[1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]]


In [ ]:
print("\nQ4.1: Calculate the sum of all prices")


In [44]:
sum = np.sum(retail_data[:,1])
print('$',sum)

$ 481.9


In [37]:
total_price = np.sum(retail_data[:, 1])
print(f"Total price: ${total_price:.2f}")


Total price: $481.90


In [ ]:
print("\nQ4.2: Calculate the mean price")


In [41]:
mean = np.mean(retail_data[:,1])
print("$",mean)

$ 48.19


In [ ]:
print("\nQ4.3: Calculate the standard deviation of prices")


In [48]:
SD = np.std(retail_data[:,1])
print(f'sd:${SD:.2f}')

sd:$24.70


In [ ]:
print("\nQ4.4: Calculate the variance of prices")


In [49]:
var = np.var(retail_data[:,1])
print(f'var:${var:.2f}')

var:$609.96


In [ ]:
print("\nQ4.5: Calculate the median price")


In [50]:
median = np.median(retail_data[:,1])
print(f'median:${median:.2f}')

median:$44.99


In [2]:
percentiles = np.percentile(retail_data[:, 1], [25, 50, 75])
print(f"25th percentile: ${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")

25th percentile: $26.99
50th percentile: $44.99
75th percentile: $67.49


In [3]:
covariance = np.cov(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Covariance: {covariance:.4f}")


Covariance: -653.4444


In [4]:
reshaped_5x10 = retail_data.reshape(5, 10)
print(reshaped_5x10)


[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [5]:
split_horizontal = np.hsplit(retail_data, 2)
print("First part:")
print(split_horizontal[0])
print("\nSecond part:")
print(split_horizontal[1])


ValueError: array split does not result in an equal division

In [6]:
expensive_products = retail_data[retail_data[:, 1] > 50]
print(expensive_products)


[[1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [7]:
price_range_count = np.sum((retail_data[:, 1] >= 20) & (retail_data[:, 1] <= 60))
print(f"Products in $20-$60 range: {price_range_count}")

Products in $20-$60 range: 5


In [8]:
rating_sort_indices = np.argsort(retail_data[:, 3])
print(rating_sort_indices)


[2 6 4 8 0 5 9 1 7 3]


In [9]:
hist_prices, bin_edges = np.histogram(retail_data[:, 1], bins=5)
print(f"Histogram counts: {hist_prices}")
print(f"Bin edges: {bin_edges}")


Histogram counts: [4 1 2 1 2]
Bin edges: [15.99 30.79 45.59 60.39 75.19 89.99]


In [10]:
normal_random = np.random.normal(0, 1, 5)
print(normal_random)

[-1.11818498  0.30263449 -0.41703343  1.50632187 -1.12916294]


In [11]:
matrix_2x2 = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(matrix_2x2)
print(f"Matrix:\n{matrix_2x2}")
print(f"Determinant: {determinant}")


Matrix:
[[2 3]
 [1 4]]
Determinant: 5.000000000000001


In [13]:
product_ids_str = retail_data[:, 0].astype(str)
print(product_ids_str)

['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [14]:
replaced_ids = np.char.replace(product_ids_str, '100', 'PROD')
print(replaced_ids)

['PROD1.0' 'PROD2.0' 'PROD3.0' 'PROD4.0' 'PROD5.0' 'PROD6.0' 'PROD7.0'
 'PROD8.0' 'PROD9.0' '1010.0']


In [15]:
price_labels = np.where(retail_data[:, 1] > 50, 'Expensive', 'Affordable')
print(price_labels)


['Affordable' 'Affordable' 'Affordable' 'Expensive' 'Affordable'
 'Expensive' 'Affordable' 'Expensive' 'Affordable' 'Expensive']


In [16]:
def low_price(x): return x * 0.9  # 10% discount
def mid_price(x): return x * 1.0  # No change
def high_price(x): return x * 1.1  # 10% markup

discounted_prices = np.piecewise(
    retail_data[:, 1],
    [retail_data[:, 1] < 20, (retail_data[:, 1] >= 20) & (retail_data[:, 1] < 50), retail_data[:, 1] >= 50],
    [low_price, mid_price, high_price]
)
print(discounted_prices)

[29.99  49.99  17.991 98.989 14.391 76.989 39.99  87.989 25.99  65.989]


In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstacked = np.hstack([arr1, arr2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Horizontally stacked: {hstacked}")


Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontally stacked: [1 2 3 4 5 6]


In [3]:
vstacked = np.vstack([arr1, arr2])
print(f"Vertically stacked:\n{vstacked}")

Vertically stacked:
[[1 2 3]
 [4 5 6]]


In [4]:
dstacked = np.dstack([arr1, arr2])
print(f"Depth-wise stacked:\n{dstacked}")

Depth-wise stacked:
[[[1 4]
  [2 5]
  [3 6]]]


In [5]:
col_stacked = np.column_stack([arr1, arr2])
print(f"Column stacked:\n{col_stacked}")

Column stacked:
[[1 4]
 [2 5]
 [3 6]]


In [6]:
arr_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_parts = np.split(arr_to_split, 3)
print(f"Original array: {arr_to_split}")
for i, part in enumerate(split_parts):
    print(f"Part {i+1}: {part}")


Original array: [1 2 3 4 5 6 7 8 9]
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [11]:
split_at_indices = np.split(arr_to_split, [2, 6])
print(f"Split at indices [2, 6]:")
for i, part in enumerate(split_at_indices):
    print(f"Part {i+1}: {part}")


Split at indices [2, 6]:
Part 1: [1 2]
Part 2: [3 4 5 6]
Part 3: [7 8 9]


In [12]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
print(f"Original 2D array:\n{arr_2d}")
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part {i+1}:\n{part}")

Original 2D array:
[[1 2 3]
 [4 5 6]]
Horizontal part 1:
[[1]
 [4]]
Horizontal part 2:
[[2]
 [5]]
Horizontal part 3:
[[3]
 [6]]


In [13]:
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:")
for i, part in enumerate(vsplit_parts):
    print(f"Part {i+1}:\n{part}")

Vertical parts:
Part 1:
[[1 2 3]]
Part 2:
[[4 5 6]]


In [14]:
chunks = np.array_split(arr_to_split, 4)
print(f"Split into 4 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}: {chunk}")


Split into 4 chunks:
Chunk 1: [1 2 3]
Chunk 2: [4 5]
Chunk 3: [6 7]
Chunk 4: [8 9]


In [15]:
repeat_elements = np.repeat(arr1, 3)
print(f"Original: {arr1}")
print(f"Repeated 3 times: {repeat_elements}")

Original: [1 2 3]
Repeated 3 times: [1 1 1 2 2 2 3 3 3]


In [19]:
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small,(2,3))
print(f"Original:\n{arr_2d_small}")
print(f"Tiled (2, 3):\n{tiled_2d}")

Original:
[[1 2]
 [3 4]]
Tiled (2, 3):
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [20]:
pattern = np.array([1, 0])
pattern_tiled = np.tile(pattern, 5)
print(f"Pattern: {pattern}")
print(f"Tiled 5 times: {pattern_tiled}")

Pattern: [1 0]
Tiled 5 times: [1 0 1 0 1 0 1 0 1 0]


In [21]:
repeat_counts = [2, 1, 3]
repeated_variable = np.repeat(arr1, repeat_counts)
print(f"Original: {arr1}")
print(f"Repeat counts: {repeat_counts}")
print(f"Result: {repeated_variable}")


Original: [1 2 3]
Repeat counts: [2, 1, 3]
Result: [1 1 2 3 3 3]


In [22]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([1, 2, 3])
arr_c = np.array([1, 2, 4])
print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Array C: {arr_c}")
print(f"A equals B: {np.array_equal(arr_a, arr_b)}")
print(f"A equals C: {np.array_equal(arr_a, arr_c)}")


Array A: [1 2 3]
Array B: [1 2 3]
Array C: [1 2 4]
A equals B: True
A equals C: False


In [23]:
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Array D: {arr_d}")
print(f"Array E: {arr_e}")
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")


Array D: [1. 2. 3.]
Array E: [1.001 2.001 3.001]
Arrays are close: True


In [24]:
logical_and = np.logical_and(arr_a > 1, arr_a < 3)
print(f"Array: {arr_a}")
print(f"Logical AND (1 < x < 3): {logical_and}")


Array: [1 2 3]
Logical AND (1 < x < 3): [False  True False]


In [25]:
logical_or = np.logical_or(arr_a == 1, arr_a == 3)
print(f"Array: {arr_a}")
print(f"Logical OR (x == 1 OR x == 3): {logical_or}")

Array: [1 2 3]
Logical OR (x == 1 OR x == 3): [ True False  True]


In [26]:
arr_f = np.array([1, 2, 3, 4])
arr_g = np.array([3, 4, 5, 6])
intersection = np.intersect1d(arr_f, arr_g)
print(f"Array F: {arr_f}")
print(f"Array G: {arr_g}")
print(f"Intersection: {intersection}")

Array F: [1 2 3 4]
Array G: [3 4 5 6]
Intersection: [3 4]


In [27]:
symmetric_diff = np.setxor1d(arr_f, arr_g)
print(f"Symmetric difference: {symmetric_diff}")

Symmetric difference: [1 2 5 6]
